services:
  fresco:
    image: "fresco"
    build: "https://github.com/urcc-ncorp/Fresco.git"
    volumes:
      - fresco_data:/app/data
    restart: always
    ports:
      - 0:3000
    env_file:
      - .env

volumes:
  fresco_data:
