# services:
#   postgres:
#     container_name: fresco-dev-postgres
#     image: postgres:16-alpine
#     restart: unless-stopped
#     ports:
#       - 5432:5432
#     env_file:
#       - .env
#     environment:
#       - POSTGRES_PASSWORD=postgres
#       - POSTGRES_USER=postgres
#     volumes:
#       - postgres:/var/lib/postgresql/data
#     healthcheck:
#       test: ["CMD", "pg_isready", '-U', 'postgres']
#       interval: 5s
#       timeout: 10s
#       retries: 5
# 
#   fresco:
#     container_name: fresco-dev
#     image: "fresco"
#     build: "https://github.com/urcc-ncorp/Fresco.git"
#     depends_on:
#       postgres:
#         condition: service_healthy
#     volumes:
#       - fresco_data:/app/data
#     restart: unless-stopped
#     ports:
#       - 0:3001
#     networks:
#       - fresco_network
#     environment:
#       DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/fresco
#       DATABASE_URL_UNPOOLED: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/fresco
#     env_file:
#       - .env
#   
#   volumes:
#     postgres:
#       name: fresco-dev-db-volume
#     fresco_data:
#   
#   # Define a network, which allows containers to communicate
#   # with each other, by using their container name as a hostname
#   networks:
#     fresco_network: